### ISSUE TITLE
I2C connectors.

### ISSUE THREAD

**Issue by kimanimichael** [nakujaproject/N2-onboardTelemetryComputer#16]
* **I'm submitting a ...**
  - [ ] bug report

Change I2C connectors from jumper wire header pins to JST connectors as currently on the avionics board. [Here](https://github.com/nakujaproject/avionicsv2/blob/reviews2/COMPUTER_PCB/Schematic_N2%20Avionics%20board.pdf)
 The pitch for the I2C connector is 1mm.

Jumper wire connections aren't firm enough.

**Comment by rodneyosodo** [comment]
The JST connectors we have available are compatible with 2.54mm header pins

@WashingtonKK Confirm on this

**Comment by rodneyosodo** [comment]
I'll stick with the header pins because:
- **Space** was a big factor. I designed for power with JST and communication without because of space.
- We already have the JST connectors here so we will just swap them if necessary
- The JST connectors we have it is tiresome to wire the female connections as it requires crimping that is why we changed from JST to header pins during the test flight
- They are quite expensive compared to the normal header pins

**Comment by kimanimichael** [comment]
Regarding the comment above:

- You seem to still have a lot of space on the bottom side.
![Screenshot from 2022-04-09 11-22-32](https://user-images.githubusercontent.com/49106674/162563402-99c85972-6f8d-407b-b838-89a69ac0ead8.png)

- We may have already been unable to acquire the data due to loose jumper wire connections. So it may already be too late to swap them.

-We can get already crimped cables.

- I don't think the difference in price is too much to ensure we don't loose data.

**Comment by kimanimichael** [comment]
Actually our main problem is acquiring JSTs with different pitch sizes.

**Comment by rodneyosodo** [comment]
I have a lot of space at the bottom since JLCPCB will be assembling only one layer which is the top layer.
